export * as IAsset from "@/asset";
export * as ICase from "@/case";
export * as IChat from "@/chat";
export * as IError from "@/error";
export * as IExamination from "@/examination";
export * as IFilter from "@/filter";
export * as IUser from "@/user";
export * as IInvestigation from "@/investigation";
export * as IConsultation from "@/consultation";
export * as ITreatment from "@/treatement";
export * from "@/utils";
export * from "@/examination";
